In [46]:
from itertools import combinations
import numpy as np
comb_list = combinations([1023, 1535, 1791,1919,1983,2015,2031,2039], 2)
x = np.array(list(comb_list))
y = np.ones((len(x),1))
z = np.hstack((x,y))
z = z.astype('int64')
print(z)
np.savetxt("z_matrix.csv", z, delimiter=',', comments="")


[[1023 1535    1]
 [1023 1791    1]
 [1023 1919    1]
 [1023 1983    1]
 [1023 2015    1]
 [1023 2031    1]
 [1023 2039    1]
 [1023 2043    1]
 [1535 1791    1]
 [1535 1919    1]
 [1535 1983    1]
 [1535 2015    1]
 [1535 2031    1]
 [1535 2039    1]
 [1535 2043    1]
 [1791 1919    1]
 [1791 1983    1]
 [1791 2015    1]
 [1791 2031    1]
 [1791 2039    1]
 [1791 2043    1]
 [1919 1983    1]
 [1919 2015    1]
 [1919 2031    1]
 [1919 2039    1]
 [1919 2043    1]
 [1983 2015    1]
 [1983 2031    1]
 [1983 2039    1]
 [1983 2043    1]
 [2015 2031    1]
 [2015 2039    1]
 [2015 2043    1]
 [2031 2039    1]
 [2031 2043    1]
 [2039 2043    1]]
